---
language: perl
perl:
  - "5.20"
  - "5.24"
  - "5.26"
  - "5.28"
services:
  - postgresql
addons:
  postgresql: "9.6"
sudo: true
env:
  - SREVIEW_TESTDB=sreview
install:
  - sudo add-apt-repository ppa:mc3man/testing6 -y && sudo apt-get update && sudo apt-get install ffmpeg inkscape bs1770gain
  - cpanm --quiet --installdeps --notest .
before_script:
  - psql -c "create database $SREVIEW_TESTDB;" -U postgres
script:
  - perl Makefile.PL && make TEST_VERBOSE=1 test
